"""connection history updated

Revision ID: 0c43f796e0d8
Revises: 5b5755e8105d
Create Date: 2023-12-28 21:29:43.722814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c43f796e0d8'
down_revision = '5b5755e8105d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updates_received', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updates_sent', sa.Integer(), nullable=True))
        batch_op.alter_column('connection_type',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.Enum('SYNC', 'RESET', name='connectiontype'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_history', schema=None) as batch_op:
        batch_op.alter_column('connection_type',
               existing_type=sa.Enum('SYNC', 'RESET', name='connectiontype'),
               type_=sa.VARCHAR(length=3),
               existing_nullable=True)
        batch_op.drop_column('updates_sent')
        batch_op.drop_column('updates_received')

    # ### end Alembic commands ###
