"""sales margin removed

Revision ID: 5b5755e8105d
Revises: 9c378d5c9118
Create Date: 2023-12-28 20:37:24.868101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b5755e8105d'
down_revision = '9c378d5c9118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('sales_margin')

    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.drop_column('sales_margin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_margin', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_margin', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
