"""raised and solved time for issues added

Revision ID: 75cd3ce370ed
Revises: c7e8c568bf38
Create Date: 2023-12-21 11:43:37.387315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75cd3ce370ed'
down_revision = 'c7e8c568bf38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raised_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('solved_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_column('solved_time')
        batch_op.drop_column('raised_time')

    # ### end Alembic commands ###
